### ISSUE TITLE
兄弟是否会继续更新？

### ISSUE THREAD

**Issue by warofkings** [hell0bird/CaiXin_weekly#3]
兄弟是否会继续更新？希望能够继续更新，感谢兄弟的共享~

**Comment by hell0bird** [comment]
> 兄弟是不是会继续更新？希望能继续更新，感谢兄弟的共享~

会的，但是github仓库有限制，在找其他方式

**Comment by tasty-x** [comment]
> > 兄弟是不是会继续更新？希望能继续更新，感谢兄弟的共享~
> 
> 会的，但是是github库有限公司，在找其他方式

是不是可以考虑一下TG，thx

**Comment by Taoup** [comment]
在哪里更新的啊

**Comment by hell0bird** [comment]
https://t.me/cxweekly

**Comment by hell0bird** [comment]
> > 兄弟是不是会继续更新？希望能继续更新，感谢兄弟的共享~
> 
> 会的，但是github仓库有限制，在找其他方式

https://t.me/cxweekly

**Comment by hell0bird** [comment]
> 在哪里更新的啊

https://t.me/cxweekly
